language: android

jdk:
 - oraclejdk8

android:
  components:
    # Update tools and then platform-tools explicitly so lint gets an updated database. Can be removed once 3.0 is out.
    # TODO verify this is no longer needed for lint to run.
    - tools
    - platform-tools
    - sys-img-armeabi-v7a-android-19

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &

install: ./gradlew clean assemble

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script: ./gradlew check connectedCheck

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

notifications:
  email: false

sudo: false
